export const PLAYER_INFORMATION = [
  { rank: "Líder Doblado", name: "Overseer", description: "", mainClass: "hunter" },
  { rank: "Rodando llego más rápido", name: "Kayn", description: "Con sus poderosísimos 135kg y 160CM de altura: arrasa (literalmente) con todos los bosses que se encuentre.", mainClass: "paladin" },
  { rank: "Mago", name: "Grump", description: "", mainClass: "paladin" },
  // { rank: "-", name: "Abu", description: "", mainClass: "druid" },
  { rank: "30 años jugando mago", name: "Airak", description: "", mainClass: "mage" },
  { rank: "Sabes que se murió porque escuchaste un ruido", name: "Ale", description: "", mainClass: "priest" },
  { rank: "ni idea", name: "Aruh", description: "", mainClass: "hunter" },
  { rank: "Amigo de Monny", name: "Damba", description: "", mainClass: "warlock" },
  { rank: "Su dolor más grande es jugar Aug", name: "Dani", description: "", mainClass: "evoker" },
  { rank: "ni idea que ponerle a deep", name: "Deep", description: "", mainClass: "paladin" },
  { rank: "ni idea", name: "Derako", description: "", mainClass: "druid" },
  { rank: "ni idea", name: "Dirty", description: "", mainClass: "shaman" },
  { rank: "Gay", name: "Fenrus", description: "", mainClass: "shaman" },
  { rank: "Gasta mas en cambio de nombre que en la suscripción", name: "Galilea", description: "", mainClass: "paladin" },
  { rank: "Lord of the Cloaks", name: "Glooms", description: "", mainClass: "warlock" },
  { rank: "ni idea", name: "Juan", description: "", mainClass: "warlock" },
  { rank: "Se pone emo cuando hablamos en chileno", name: "Kina", description: "", mainClass: "priest" },
  { rank: "Representante del Edén de México", name: "Kreic", description: "", mainClass: "dh" },
  { rank: "ni idea", name: "Mntsu", description: "", mainClass: "monk" },
  { rank: "Xmog Police Member", name: "Nekon", description: "", mainClass: "rogue" },
  { rank: "Cat Hoarder", name: "Pansito", description: "", mainClass: "dh" },
  { rank: "Intérprete oficial de la guild", name: "Sakimo", description: "", mainClass: "dk" },
  { rank: "Xmog Police Member", name: "Wizza", description: "", mainClass: "warrior" },
  { rank: "Ignora a Kayn", name: "🫏", description: "", mainClass: "shaman" },
];