export const PLAYER_INFORMATION = [
  { rank: "GAY LEADER", name: "Kayn", description: "Despues de haber conseguido multiples realm first y world firsts, nos deleita contando sus historias y azanas en la gran guild Poptar Corndog, siempre que tengas la oportunidad de hablar con el recuerda, el estuvo alli!", mainClass: "paladin" },
  { rank: "GUILD LEADER", name: "Overseer", description: "Con la cara doblada, cargo a toda Latino America reuniendo a las personas con mas habilidad en una unica, hermosa e irremplazable guild llamada Ascended", mainClass: "hunter" },
  { rank: "OFFICER", name: "Grump", description: "Su versatilidad con las clases se contradice en la versatilidad de su corte de pelo. Si alguna vez dudaron que podrian encontrar un negro pelirrojo, no se preocupe. Si existe un peruano afro, seguramente existe un negro pelirrojo.", mainClass: "paladin" },
  { rank: "-", name: "Abu", description: "", mainClass: "druid" },
  { rank: "-", name: "Airak", description: "", mainClass: "mage" },
  { rank: "-", name: "Ale", description: "", mainClass: "priest" },
  { rank: "-", name: "Aruh", description: "", mainClass: "hunter" },
  { rank: "-", name: "Damba", description: "", mainClass: "warlock" },
  { rank: "-", name: "Dani", description: "", mainClass: "evoker" },
  { rank: "-", name: "Deep", description: "", mainClass: "paladin" },
  { rank: "-", name: "Derako", description: "", mainClass: "druid" },
  { rank: "-", name: "Dirty", description: "", mainClass: "shaman" },
  { rank: "-", name: "Fenrus", description: "", mainClass: "shaman" },
  { rank: "-", name: "Galilea", description: "", mainClass: "paladin" },
  { rank: "-", name: "Glooms", description: "", mainClass: "warlock" },
  { rank: "-", name: "Juan", description: "", mainClass: "warlock" },
  { rank: "-", name: "Kina", description: "", mainClass: "priest" },
  { rank: "-", name: "Kreic", description: "", mainClass: "dh" },
  { rank: "-", name: "Mntsu", description: "", mainClass: "monk" },
  { rank: "-", name: "Nekon", description: "", mainClass: "rogue" },
  { rank: "-", name: "Pansito", description: "", mainClass: "dh" },
  { rank: "-", name: "Sakimo", description: "", mainClass: "dk" },
  { rank: "-", name: "Wizza", description: "", mainClass: "warrior" },
  { rank: "-", name: "🫏", description: "", mainClass: "shaman" },
];