import * as CLASSES from "../assets/smallClassIcons/smallClassIcons"
import * as ROLE_ICONS from "../assets/roleIcons/roleIcons"

export const CLASS_NAMES = [
  { wowClass: "DK", value: "DK", icon: CLASSES.dkIcon },
  { wowClass: "DH", value: "DH", icon: CLASSES.dhIcon },
  { wowClass: "Druid", value: "Druid", icon: CLASSES.druidIcon },
  { wowClass: "Evoker", value: "Evoker", icon: CLASSES.evokerIcon },
  { wowClass: "Hunter", value: "Hunter", icon: CLASSES.hunterIcon },
  { wowClass: "Mage", value: "Mage", icon: CLASSES.mageIcon },
  { wowClass: "Monk", value: "Monk", icon: CLASSES.monkIcon },
  { wowClass: "Paladin", value: "Paladin", icon: CLASSES.paladinIcon },
  { wowClass: "Priest", value: "Priest", icon: CLASSES.priestIcon },
  { wowClass: "Rogue", value: "Rogue", icon: CLASSES.rogueIcon },
  { wowClass: "Shaman", value: "Shaman", icon: CLASSES.shamanIcon },
  { wowClass: "Warlock", value: "Warlock", icon: CLASSES.warlockIcon },
  { wowClass: "Warrior", value: "Warrior", icon: CLASSES.warriorIcon },
];

export const ROLE_NAMES = [
  { value: "Tank", icon: ROLE_ICONS.tankIcon },
  { value: "Healer", icon: ROLE_ICONS.healerIcon },
  { value: "DPS", icon: ROLE_ICONS.dpsIcon },
];

export const REALM_LIST = [
  "Aegwynn",
  "Aerie Peak",
  "Agamaggan",
  "Aggramar",
  "Akama",
  "Alexstrasza",
  "Alleria",
  "Altar of Storms",
  "Alterac Mountains",
  "Aman'Thul",
  "Andorhal",
  "Anetheron",
  "Antonidas",
  "Anub'arak",
  "Anvilmar",
  "Arathor",
  "Archimonde",
  "Area 52",
  "Argent Dawn",
  "Arthas",
  "Arygos",
  "Auchindoun",
  "Azgalor",
  "Azjol-Nerub",
  "Azralon",
  "Azshara",
  "Azuremyst",
  "Baelgun",
  "Balnazzar",
  "Barthilas",
  "Black Dragonflight",
  "Blackhand",
  "Blackrock",
  "Blackwater Raiders",
  "Blackwing Lair",
  "Blade's Edge",
  "Bladefist",
  "Bleeding Hollow",
  "Blood Furnace",
  "Bloodhoof",
  "Bloodscalp",
  "Bonechewer",
  "Borean Tundra",
  "Boulderfist",
  "Bronzebeard",
  "Burning Blade",
  "Burning Legion",
  "Caelestrasz",
  "Cairne",
  "Cenarion Circle",
  "Cenarius",
  "Cho'gall",
  "Chromaggus",
  "Coilfang",
  "Crushridge",
  "Daggerspine",
  "Dalaran",
  "Dalvengyr",
  "Dark Iron",
  "Darkspear",
  "Darrowmere",
  "Dath'Remar",
  "Dawnbringer",
  "Deathwing",
  "Demon Soul",
  "Dentarg",
  "Destromath",
  "Dethecus",
  "Detheroc",
  "Doomhammer",
  "Draenor",
  "Dragonblight",
  "Dragonmaw",
  "Drak'Tharon",
  "Draka",
  "Drakkari",
  "Dreadmaul",
  "Drenden",
  "Dunemaul",
  "Durotan",
  "Duskwood",
  "Earthen Ring",
  "Echo Isles",
  "Eitrigg",
  "Eldre'Thalas",
  "Elune",
  "Emerald Dream",
  "Eonar",
  "Eredar",
  "Executus",
  "Exodar",
  "Farstriders",
  "Feathermoon",
  "Fenris",
  "Firetree",
  "Fizzcrank",
  "Galakrond",
  "Garithos",
  "Garona",
  "Garrosh",
  "Ghostlands",
  "Gilneas",
  "Gnomeregan",
  "Goldrinn",
  "Gorefiend",
  "Gorgonnash",
  "Greymane",
  "Grizzly Hills",
  "Gul'dan",
  "Hakkar",
  "Haomarush",
  "Hellscream",
  "Hydraxis",
  "Hyjal",
  "Icecrown",
  "Illidan",
  "Jaedenar",
  "Jubei'Thos",
  "Kael'thas",
  "Kalecgos",
  "Kargath",
  "Kel'Thuzad",
  "Khadgar",
  "Khaz Modan",
  "Khaz'goroth",
  "Kil'jaeden",
  "Kilrogg",
  "Kirin Tor",
  "Korgath",
  "Korialstrasz",
  "Kul Tiras",
  "Laughing Skull",
  "Lethon",
  "Lightbringer",
  "Lightning's Blade",
  "Lightninghoof",
  "Llane",
  "Lothar",
  "Madoran",
  "Maelstrom",
  "Magtheridon",
  "Maiev",
  "Mal'Ganis",
  "Malfurion",
  "Malorne",
  "Malygos",
  "Mannoroth",
  "Medivh",
  "Misha",
  "Moon Guard",
  "Moonrunner",
  "Mug'thol",
  "Nagrand",
  "Nazgrel",
  "Nazjatar",
  "Ner'zhul",
  "Nesingwary",
  "Nordrassil",
  "Norgannon",
  "Onyxia",
  "Perenolde",
  "Proudmoore",
  "Quel'dorei",
  "Quel'Thalas",
  "Ragnaros",
  "Ravencrest",
  "Ravenholdt",
  "Rexxar",
  "Rivendare",
  "Runetotem",
  "Sargeras",
  "Saurfang",
  "Scarlet Crusade",
  "Scilla",
  "Sen'jin",
  "Sentinels",
  "Shadow Council",
  "Shadowmoon",
  "Shadowsong",
  "Shandris",
  "Shattered Halls",
  "Shattered Hand",
  "Shu'halo",
  "Silver Hand",
  "Silvermoon",
  "Sisters of Elune",
  "Skullcrusher",
  "Skywall",
  "Smolderthorn",
  "Spinebreaker",
  "Spirestone",
  "Staghelm",
  "Steamwheedle Cartel",
  "Stonemaul",
  "Stormrage",
  "Stormreaver",
  "Stormscale",
  "Suramar",
  "Tanaris",
  "Terenas",
  "Terokkar",
  "Thaurissan",
  "The Forgotten Coast",
  "The Scryers",
  "The Underbog",
  "The Venture Co",
  "Thorium Brotherhood",
  "Thrall",
  "Thunderhorn",
  "Thunderlord",
  "Tichondrius",
  "Tol Barad",
  "Tortheldrin",
  "Trollbane",
  "Turalyon",
  "Uldaman",
  "Uldum",
  "Undermine",
  "Ursin",
  "Vashj",
  "Vek'nilash",
  "Velen",
  "Warsong",
  "Whisperwind",
  "Wildhammer",
  "Windrunner",
  "Winterhoof",
  "Wyrmrest Accord",
  "Ysera",
  "Ysondre",
  "Zangarmarsh",
  "Zul'jin",
  "Zuluhed"
];