import * as CLASS_ICONS from "../assets/classIcons/index"

const WOW_CLASSES = [
  { wowClass: "Death Knight", spec: "Blood", key: "bloodDeathKnight", icon: CLASS_ICONS.deathKnightIcon },
  { wowClass: "Death Knight", spec: "Frost", key: "frostDeathKnight", icon: CLASS_ICONS.deathKnightIcon },
  { wowClass: "Death Knight", spec: "Unholy", key: "unholyDeathKnight", icon: CLASS_ICONS.deathKnightIcon },
  { wowClass: "Demon Hunter", spec: "Devourer", key: "devourerDemonHunter", icon: CLASS_ICONS.demonHunterIcon },
  { wowClass: "Demon Hunter", spec: "Havoc", key: "havocDemonHunter", icon: CLASS_ICONS.demonHunterIcon },
  { wowClass: "Demon Hunter", spec: "Vengeance", key: "vengeanceDemonHunter", icon: CLASS_ICONS.demonHunterIcon },
  { wowClass: "Druid", spec: "Balance", key: "balanceDruid", icon: CLASS_ICONS.druidIcon },
  { wowClass: "Druid", spec: "Feral", key: "feralDruid", icon: CLASS_ICONS.druidIcon },
  { wowClass: "Druid", spec: "Guardian", key: "guardianDruid", icon: CLASS_ICONS.druidIcon },
  { wowClass: "Druid", spec: "Restoration", key: "restorationDruid", icon: CLASS_ICONS.druidIcon },
  { wowClass: "Hunter", spec: "Beast Mastery", key: "beastMasteryHunter", icon: CLASS_ICONS.hunterIcon },
  { wowClass: "Hunter", spec: "Marksmanship", key: "marksmanshipHunter", icon: CLASS_ICONS.hunterIcon },
  { wowClass: "Hunter", spec: "Survival", key: "survivalHunter", icon: CLASS_ICONS.hunterIcon },
  { wowClass: "Mage", spec: "Arcane", key: "arcaneMage", icon: CLASS_ICONS.mageIcon },
  { wowClass: "Mage", spec: "Fire", key: "fireMage", icon: CLASS_ICONS.mageIcon },
  { wowClass: "Mage", spec: "Frost", key: "frostMage", icon: CLASS_ICONS.mageIcon },
  { wowClass: "Monk", spec: "Brewmaster", key: "brewmasterMonk", icon: CLASS_ICONS.monkIcon },
  { wowClass: "Monk", spec: "Mistweaver", key: "mistweaverMonk", icon: CLASS_ICONS.monkIcon },
  { wowClass: "Monk", spec: "Windwalker", key: "windwalkerMonk", icon: CLASS_ICONS.monkIcon },
  { wowClass: "Paladin", spec: "Holy", key: "holyPaladin", icon: CLASS_ICONS.paladinIcon },
  { wowClass: "Paladin", spec: "Protection", key: "protectionPaladin", icon: CLASS_ICONS.paladinIcon },
  { wowClass: "Paladin", spec: "Retribution", key: "retributionPaladin", icon: CLASS_ICONS.paladinIcon },
  { wowClass: "Priest", spec: "Discipline", key: "disciplinePriest", icon: CLASS_ICONS.priestIcon },
  { wowClass: "Priest", spec: "Holy", key: "holyPriest", icon: CLASS_ICONS.priestIcon },
  { wowClass: "Priest", spec: "Shadow", key: "shadowPriest", icon: CLASS_ICONS.priestIcon },
  { wowClass: "Rogue", spec: "Assasination", key: "assasinationRogue", icon: CLASS_ICONS.rogueIcon },
  { wowClass: "Rogue", spec: "Outlaw", key: "outlawRogue", icon: CLASS_ICONS.rogueIcon },
  { wowClass: "Rogue", spec: "Subtlety", key: "subtletyRogue", icon: CLASS_ICONS.rogueIcon },
  { wowClass: "Shaman", spec: "Elemental", key: "elementalShaman", icon: CLASS_ICONS.shamanIcon },
  { wowClass: "Shaman", spec: "Enhancement", key: "enhancementShaman", icon: CLASS_ICONS.shamanIcon },
  { wowClass: "Shaman", spec: "Restoration", key: "restorationShaman", icon: CLASS_ICONS.shamanIcon },
  { wowClass: "Warlock", spec: "Affliction", key: "afflictionWarlock", icon: CLASS_ICONS.warlockIcon },
  { wowClass: "Warlock", spec: "Demonology", key: "demonologyWarlock", icon: CLASS_ICONS.warlockIcon },
  { wowClass: "Warlock", spec: "Destruction", key: "destructionWarlock", icon: CLASS_ICONS.warlockIcon },
  { wowClass: "Warrior", spec: "Arms", key: "armsWarrior", icon: CLASS_ICONS.warriorIcon },
  { wowClass: "Warrior", spec: "Fury", key: "furyWarrior", icon: CLASS_ICONS.warriorIcon },
  { wowClass: "Warrior", spec: "Protection", key: "protecitonWarrior", icon: CLASS_ICONS.warriorIcon },
];

export default WOW_CLASSES;