const WOW_CLASSES = [
  "DK - Blood",
  "DK - Frost",
  "DK - Unholy",
  "DH - Havoc",
  "DH - Vengeance",
  "Druid - Balance",
  "Druid - Feral",
  "Druid - Guardian",
  "Druid - Restoration",
  "Hunter - Beast Mastery",
  "Hunter - Marksmanship",
  "Hunter - Survival",
  "Mage - Arcane",
  "Mage - Fire",
  "Mage - Frost",
  "Monk - Brewmaster",
  "Monk - Mistweaver",
  "Monk - Windwalker",
  "Paladin - Holy",
  "Paladin - Protection",
  "Paladin - Retribution",
  "Priest - Discipline",
  "Priest - Holy",
  "Priest - Shadow",
  "Rogue - Assassination",
  "Rogue - Outlaw",
  "Rogue - Subtlety",
  "Shaman - Elemental",
  "Shaman - Enhancement",
  "Shaman - Restoration",
  "Warlock - Affliction",
  "Warlock - Demonology",
  "Warlock - Destruction",
  "Warrior - Arms",
  "Warrior - Fury",
  "Warrior - Protection",
];

export default WOW_CLASSES;