import * as CLASS_ICONS from "../assets/classIcons/index"

const WOW_CLASSES = [
  { wowClass: "Death Knight", spec: "Blood", icon: CLASS_ICONS.deathKnightIcon },
  { wowClass: "Death Knight", spec: "Frost", icon: CLASS_ICONS.deathKnightIcon },
  { wowClass: "Death Knight", spec: "Unholy", icon: CLASS_ICONS.deathKnightIcon },
  { wowClass: "Demon Hunter", spec: "Devourer", icon: CLASS_ICONS.demonHunterIcon },
  { wowClass: "Demon Hunter", spec: "Havoc", icon: CLASS_ICONS.demonHunterIcon },
  { wowClass: "Demon Hunter", spec: "Vengeance", icon: CLASS_ICONS.demonHunterIcon },
  { wowClass: "Druid", spec: "Balance", icon: CLASS_ICONS.druidIcon },
  { wowClass: "Druid", spec: "Feral", icon: CLASS_ICONS.druidIcon },
  { wowClass: "Druid", spec: "Guardian", icon: CLASS_ICONS.druidIcon },
  { wowClass: "Druid", spec: "Restoration", icon: CLASS_ICONS.druidIcon },
  { wowClass: "Hunter", spec: "Beast Mastery", icon: CLASS_ICONS.hunterIcon },
  { wowClass: "Hunter", spec: "Marksmanship", icon: CLASS_ICONS.hunterIcon },
  { wowClass: "Hunter", spec: "Survival", icon: CLASS_ICONS.hunterIcon },
  { wowClass: "Mage", spec: "Arcane", icon: CLASS_ICONS.mageIcon },
  { wowClass: "Mage", spec: "Fire", icon: CLASS_ICONS.mageIcon },
  { wowClass: "Mage", spec: "Frost", icon: CLASS_ICONS.mageIcon },
  { wowClass: "Monk", spec: "Brewmaster", icon: CLASS_ICONS.monkIcon },
  { wowClass: "Monk", spec: "Mistweaver", icon: CLASS_ICONS.monkIcon },
  { wowClass: "Monk", spec: "Windwalker", icon: CLASS_ICONS.monkIcon },
  { wowClass: "Paladin", spec: "Holy", icon: CLASS_ICONS.paladinIcon },
  { wowClass: "Paladin", spec: "Protection", icon: CLASS_ICONS.paladinIcon },
  { wowClass: "Paladin", spec: "Retribution", icon: CLASS_ICONS.paladinIcon },
  { wowClass: "Priest", spec: "Discipline", icon: CLASS_ICONS.priestIcon },
  { wowClass: "Priest", spec: "Holy", icon: CLASS_ICONS.priestIcon },
  { wowClass: "Priest", spec: "Shadow", icon: CLASS_ICONS.priestIcon },
  { wowClass: "Rogue", spec: "Assasination", icon: CLASS_ICONS.rogueIcon },
  { wowClass: "Rogue", spec: "Outlaw", icon: CLASS_ICONS.rogueIcon },
  { wowClass: "Rogue", spec: "Subtlety", icon: CLASS_ICONS.rogueIcon },
  { wowClass: "Shaman", spec: "Elemental", icon: CLASS_ICONS.shamanIcon },
  { wowClass: "Shaman", spec: "Enhancement", icon: CLASS_ICONS.shamanIcon },
  { wowClass: "Shaman", spec: "Restoration", icon: CLASS_ICONS.shamanIcon },
  { wowClass: "Warlock", spec: "Affliction", icon: CLASS_ICONS.warlockIcon },
  { wowClass: "Warlock", spec: "Demonology", icon: CLASS_ICONS.warlockIcon },
  { wowClass: "Warlock", spec: "Destruction", icon: CLASS_ICONS.warlockIcon },
  { wowClass: "Warrior", spec: "Arms", icon: CLASS_ICONS.warriorIcon },
  { wowClass: "Warrior", spec: "Fury", icon: CLASS_ICONS.warriorIcon },
  { wowClass: "Warrior", spec: "Protection", icon: CLASS_ICONS.warriorIcon },
];

export default WOW_CLASSES;