export { default as kayn1 } from "./kayn1.png"
export { default as kayn2 } from "./kayn2.png"
export { default as kayn3 } from "./kayn3.png"
export { default as over1 } from "./over1.png"
export { default as over2 } from "./over2.png"
export { default as over3 } from "./over3.png"
export { default as grump1 } from "./grump1.png"
export { default as grump2 } from "./grump2.png"
export { default as grump3 } from "./grump3.png"
// export { } from ""