export { default as dkIcon } from "./classicon_deathknight.jpg"
export { default as dhIcon } from "./classicon_demonhunter (1).jpg"
export { default as druidIcon } from "./classicon_druid (1).jpg"
export { default as evokerIcon } from "./classicon_evoker (1).jpg"
export { default as hunterIcon } from "./classicon_hunter (1).jpg"
export { default as mageIcon } from "./classicon_mage (1).jpg"
export { default as monkIcon } from "./classicon_monk (1).jpg"
export { default as paladinIcon } from "./classicon_paladin.jpg"
export { default as priestIcon } from "./classicon_priest (1).jpg"
export { default as rogueIcon } from "./classicon_rogue (1).jpg"
export { default as shamanIcon } from "./classicon_shaman (1).jpg"
export { default as warlockIcon } from "./classIcon_warlock.jpg"
export { default as warriorIcon } from "./classicon_warrior (1).jpg"